#!/usr/bin/env python3
import argparse
import collections
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import recipe_contract as rc

DOC = pathlib.Path("references/entities.md")


def render(recipes_dir):
    waiting = collections.Counter()
    only = collections.Counter()
    for path in rc.recipe_paths(recipes_dir):
        front, _ = rc.read(path)
        _, wait = rc.availability(front)
        waiting.update(wait)
        if len(wait) == 1:
            only[wait[0]] += 1
    lines = [
        "# Entities",
        "",
        "<!-- generated by scripts/render_entities_doc.py; do not hand edit -->",
        "",
        f"What a step can `builds`. Snapshot of `{rc.ENGINE_REF}`.",
        "",
        "## Install now: the engine builds these today",
        "",
        "| builds | What it makes |",
        "|---|---|",
    ]
    lines += [f"| `{k}` | {v} |" for k, v in rc.BUILDABLE_ENTITIES.items()]
    lines += [
        "",
        "## Coming soon: waiting on an engine builder",
        "",
        "Recipes waiting: recipes in this repo that need the builder. Only blocker for: recipes that need nothing else.",
        "",
        "| builds | What it makes | Recipes waiting | Only blocker for |",
        "|---|---|---|---|",
    ]
    for k, v in sorted(rc.COMING_SOON_ENTITIES.items(), key=lambda kv: (-waiting[kv[0]], kv[0])):
        lines.append(f"| `{k}` | {v} | {waiting[k]} | {only[k]} |")
    lines += [
        "",
        "When the engine adds a builder, move its row from `COMING_SOON_ENTITIES` to `BUILDABLE_ENTITIES` in "
        "`scripts/recipe_contract.py` and re-run this script. Recipes waiting only on it become Install now on the next catalog build.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--recipes", default="recipes", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    wanted = render(args.recipes)
    if args.check:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != wanted:
            print(f"{DOC} is stale. Run scripts/render_entities_doc.py", file=sys.stderr)
            return 1
        print(f"{DOC} matches the recipes")
        return 0
    DOC.write_text(wanted, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
