#!/usr/bin/env python3
import argparse
import collections
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import recipe_contract as rc

DOC = pathlib.Path("references/entities.md")
COMING_SOON_DOC = pathlib.Path("references/entities/coming-soon.md")


def tally(recipes_dir):
    waiting = collections.Counter()
    only = collections.Counter()
    for path in rc.recipe_paths(recipes_dir):
        front, _ = rc.read(path)
        _, wait = rc.availability(front)
        waiting.update(wait)
        if len(wait) == 1:
            only[wait[0]] += 1
    return waiting, only


def render(recipes_dir):
    waiting, only = tally(recipes_dir)
    lines = [
        "# Entities",
        "",
        "<!-- generated by scripts/render_entities_doc.py; do not hand edit -->",
        "",
        f"What a step can `builds`. Snapshot of `{rc.ENGINE_REF}`.",
        "",
        "How to write a step for each one: [entities/README.md](entities/README.md).",
        "",
        "## Install now: the engine builds these today",
        "",
        "| builds | What it makes |",
        "|---|---|",
    ]
    lines += [f"| `{k}` | {v} |" for k, v in rc.BUILDABLE_ENTITIES.items()]
    lines += [
        "",
        "## Coming soon: waiting on an engine builder",
        "",
        "Recipes waiting: recipes in this repo that need the builder. Only blocker for: recipes that need nothing else.",
        "",
        "| builds | What it makes | Recipes waiting | Only blocker for |",
        "|---|---|---|---|",
    ]
    for k, v in sorted(rc.COMING_SOON_ENTITIES.items(), key=lambda kv: (-waiting[kv[0]], kv[0])):
        lines.append(f"| `{k}` | {v} | {waiting[k]} | {only[k]} |")
    lines += [
        "",
        "When the engine adds a builder, move its row from `COMING_SOON_ENTITIES` to `BUILDABLE_ENTITIES` in "
        "`scripts/recipe_contract.py` and re-run this script. Recipes waiting only on it become Install now on the next catalog build.",
        "",
    ]
    return "\n".join(lines)


def render_coming_soon(recipes_dir):
    waiting, only = tally(recipes_dir)
    commands = collections.defaultdict(list)
    for command, builds in rc.COMMAND_TO_BUILDS.items():
        commands[builds].append(command)
    lines = [
        "# Coming soon",
        "",
        "<!-- generated by scripts/render_entities_doc.py; do not hand edit -->",
        "",
        f"What a step can say it `builds` but the engine cannot build yet. Snapshot of `{rc.ENGINE_REF}`.",
        "",
        "Each one waits on the same thing: a builder for it in the engine's recipe allowlist. Until then a step that "
        "builds it keeps its real `builds` value, and the recipe is Coming soon and names it in `waitingOn`.",
        "",
        "| builds | What it makes | Commands listed for it in `COMMAND_TO_BUILDS` | Recipes waiting | Only blocker for |",
        "|---|---|---|---|---|",
    ]
    for k, v in sorted(rc.COMING_SOON_ENTITIES.items(), key=lambda kv: (-waiting[kv[0]], kv[0])):
        mapped = ", ".join(f"`{c}`" for c in sorted(commands.get(k, []))) or "none listed"
        lines.append(f"| `{k}` | {v} | {mapped} | {waiting[k]} | {only[k]} |")
    lines += [
        "",
        "Recipes waiting: recipes in this repo that need the builder. Only blocker for: recipes that need nothing else, "
        "and flip to Install now the day it ships.",
        "",
        "## Writing a step for one of these",
        "",
        "Write it to the same bar as an Install now step: one thing, every value written out, earlier steps by title "
        "with `dependsOn`. It will run unchanged when the builder ships. Say in the conversation that it is waiting, "
        "and never swap in an Install now entity that does something different. "
        "[../../NO-ENTITY-EXISTS.md](../../NO-ENTITY-EXISTS.md) has the jobs people ask for most and what to do instead.",
        "",
        "When the engine adds a builder, move its row from `COMING_SOON_ENTITIES` to `BUILDABLE_ENTITIES` in "
        "`scripts/recipe_contract.py`, re-run `scripts/render_entities_doc.py`, and add the entity to a family page in "
        "[README.md](README.md).",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--recipes", default="recipes", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    docs = {DOC: render(args.recipes), COMING_SOON_DOC: render_coming_soon(args.recipes)}
    if args.check:
        stale = [d for d, wanted in docs.items() if not d.exists() or d.read_text(encoding="utf-8") != wanted]
        for d in stale:
            print(f"{d} is stale. Run scripts/render_entities_doc.py", file=sys.stderr)
        if stale:
            return 1
        print(f"{DOC} and {COMING_SOON_DOC} match the recipes")
        return 0
    for d, wanted in docs.items():
        d.parent.mkdir(parents=True, exist_ok=True)
        d.write_text(wanted, encoding="utf-8")
        print(f"wrote {d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
